export const placeOrderActionTypes = {
  SET_PLACE_VAL: "SET_PLACE_VAL",
  CLEAN_PLACE_VALS: "CLEAN_PLACE_VALS",
  CHOSE_PAYMENT_METHOD: "CHOSE_PAYMENT_METHOD",
  SET_PLACE_LOADING: "SET_PLACE_LOADING",
  SET_ORDER_PLACED: "SET_ORDER_PLACED",
  SET_VERIFYING: "SET_VERIFYING",
};

export const {
  SET_PLACE_VAL,
  CLEAN_PLACE_VALS,
  CHOSE_PAYMENT_METHOD,
  SET_PLACE_LOADING,
  SET_ORDER_PLACED,
  SET_VERIFYING,
} = placeOrderActionTypes;
