export const productsActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",

  SET_PRODUCTS_LOADING: "SET_PRODUCTS_LOADING",
  SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",

  SET_PRODUCT_ITEM: "SET_PRODUCT_ITEM",

  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",

  SET_ORDER_SORTER: "SET_ORDER_SORTER",

  CHANGE_FILTERS: "CHANGE_FILTERS",

  SET_VISIBLE_SEARCH: "SET_VISIBLE_SEARCH",
  CLEAN_SEARCH: "CLEAN_SEARCH",
};

export const {
  SET_PRODUCTS,
  SET_PRODUCTS_LOADING,
  SET_PRODUCTS_ERROR,
  SET_PRODUCT_ITEM,
  SET_FILTERED_PRODUCTS,
  SET_ORDER_SORTER,
  SET_VISIBLE_SEARCH,
  CLEAN_SEARCH,
  CHANGE_FILTERS,
} = productsActionTypes;
