const ordersActionTypes = {
  SET_ORDERS: "SET_ORDERS",
  SET_ORDERS_LOADING: "SET_ORDERS_LOADING",
  SET_ORDERS_ERROR: "SET_ORDERS_ERROR",
  SET_SUCCESS_UPDATE: "SET_SUCCESS_UPDATE",
};

export const {
  SET_ORDERS,
  SET_ORDERS_LOADING,
  SET_ORDERS_ERROR,
  SET_SUCCESS_UPDATE,
} = ordersActionTypes;
