export const productsActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",

  SET_PRODUCTS_LOADING: "SET_PRODUCTS_LOADING",
  SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",

  SET_VAL_ADD_FORM: "SET_VAL_ADD_FORM",
  TOGGLE_SIZE: "TOGGLE_SIZE",
  CLEAN_FORM: "CLEAN_FORM",
  CLEAN_ADD_FORM: "CLEAN_FORM",
  PRODUCT_DELETED: "PRODUCT_DELETED",
};

export const {
  SET_PRODUCTS,
  TOGGLE_SIZE,
  SET_PRODUCTS_LOADING,
  SET_PRODUCTS_ERROR,
  SET_VAL_ADD_FORM,
  CLEAN_ADD_FORM,
  CLEAN_FORM,
  PRODUCT_DELETED,
} = productsActionTypes;
